version: '3.2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src_web:/var/www/html
    networks:
      - app-network
    ports:
      - "8081:80"
    depends_on:
      - mysql
    links:
      - mysql:mysql
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 8.8.4.4
      
  mysql:
    image: mysql:8.0
    networks:
      - app-network
    dns:
      - 127.0.0.1
    environment:
      MYSQL_ROOT_PASSWORD: shroot
      MYSQL_DATABASE: tmp1
      MYSQL_USER: newuser
      MYSQL_PASSWORD: p4$$w0rd!_!
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize the database
      - mysql_data:/var/lib/mysql  # Persist MySQL data
    

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
