version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    ports:
      - 8080:80
    links:
      - mysql:mysql
    dns:
      - 127.0.0.1
  mysql:
    image: mysql:8.0
    networks:
      - app-network
    ports:
      - 3306:3306
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: asdjiAS8153ijnasdP
      MYSQL_DATABASE: games
      MYSQL_USER: game_user
      MYSQL_PASSWORD: Giraffe#LemonTree88!
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
  python-app:
    build:
      context: .
      dockerfile: Dockerfile.python
    depends_on:
      - web
    environment:
      - CHROME_BINARY=/usr/bin/google-chrome
      - DISPLAY=:99
    networks:
      - app-network
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    links:
      - web:web
    command: bash -c "Xvfb :99 -screen 0 1024x768x24 & python3 ad.py"
volumes:
  mysql_data:
networks:
  app-network:
    driver: bridge
